# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-latest"
  jobs:
    pre_create_environment:
    - conda install -y -c conda-forge conda-merge
    - conda-merge ci/environment-ci.yml environment.yml > ci/combined-environment.yml
    - echo "Merged environment ready at ci/combined-environment.yml"
      

# Use the merged Conda environment
conda:
  environment: ci/combined-environment.yml

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Optional: install extra Python packages via pip
# python:
#   install:
#     - method: pip
#       path: .
#       extra_requirements:
#         - docs

