channels:
- conda-forge
- nodefaults
dependencies:
# Dependencies for the earthkit-transforms modules
- xarray
- numpy
- rasterio
- pip
- pip:
  - earthkit-data[all]
  - earthkit-plots
  # TODO: Revert to PyPi when available
  - "earthkit-utils @ git+https://github.com/ecmwf/earthkit-utils@develop"
  # - earthkit-utils
