# environment-ci.yml: Additional dependencies to install in the CI environment.
channels:
- conda-forge
- nodefaults
dependencies:
# Dependencies for general development
- pre-commit
- make
# Dependencies for documentation
- furo
- myst-parser
- sphinx-rtd-theme
- sphinx
- sphinx-autoapi
- nbsphinx
- sphinx-design
- ipykernel
# Required for notebook example
- statsmodels
# Dependencies for type checking
- mypy
- pandas-stubs
# Dependencies for units tests
- pytest
- pytest-cov