#!/usr/bin/env python
"""Clean up sphinx-apidoc generated RST files.

This script post-processes the RST files generated by sphinx-apidoc to:
1. Remove private modules (those starting with '_')
2. Remove hidden modules (configured in conf.py)
3. Update toctree entries to use short display names in the sidebar
   while keeping full module paths as page titles
"""

import re
from pathlib import Path

# Import configuration from conf.py
import conf

DOCS_DIR = Path(__file__).parent
AUTODOCS_DIR = DOCS_DIR / "autodocs"
MODULE_PREFIX = "earthkit.transforms"


def get_hidden_modules() -> list[str]:
    """Get the list of hidden modules from conf.py."""
    return getattr(conf, "autodocs_hidden_modules", [])


def is_private_module(module_name: str) -> bool:
    """Check if a module is private (starts with '_')."""
    # Get the last part of the module name
    parts = module_name.split(".")
    return any(part.startswith("_") for part in parts)


def should_hide_module(module_name: str, hidden_modules: list[str]) -> bool:
    """Check if a module should be hidden from documentation.

    Args:
        module_name: Full module name (e.g., 'earthkit.transforms.aggregate')
        hidden_modules: List of module names to hide (relative to earthkit.transforms)

    Returns:
        True if the module should be hidden.
    """
    if is_private_module(module_name):
        return True

    # Check against hidden modules list
    for hidden in hidden_modules:
        full_hidden = f"{MODULE_PREFIX}.{hidden}"
        # Match exact module or submodules
        if module_name == full_hidden or module_name.startswith(f"{full_hidden}."):
            return True

    return False


def get_short_name(module_name: str) -> str:
    """Get the short display name for a module.

    Args:
        module_name: Full module name (e.g., 'earthkit.transforms.temporal')

    Returns:
        Short name (e.g., 'temporal')
    """
    if module_name.startswith(f"{MODULE_PREFIX}."):
        return module_name[len(MODULE_PREFIX) + 1 :]
    return module_name


def clean_toctree(content: str, hidden_modules: list[str]) -> str:
    """Clean up toctree entries in RST content.

    - Removes entries for hidden/private modules
    - Updates entries to use short display names: 'temporal <earthkit.transforms.temporal>'

    Args:
        content: RST file content
        hidden_modules: List of module names to hide

    Returns:
        Updated RST content
    """
    lines = content.split("\n")
    result_lines = []
    in_toctree = False
    toctree_indent = ""

    for line in lines:
        # Detect start of toctree directive
        if ".. toctree::" in line:
            in_toctree = True
            result_lines.append(line)
            continue

        if in_toctree:
            # Check if we're still in the toctree (indented content or empty line)
            stripped = line.lstrip()
            current_indent = line[: len(line) - len(stripped)]

            # If line is not empty and not indented, we've left the toctree
            if stripped and not line.startswith(" ") and not line.startswith("\t"):
                in_toctree = False
                result_lines.append(line)
                continue

            # Skip empty lines within toctree
            if not stripped:
                result_lines.append(line)
                continue

            # Check if this is a toctree option (starts with :)
            if stripped.startswith(":"):
                result_lines.append(line)
                continue

            # This is a toctree entry - extract the module name
            # Entries can be in format: "module.name" or "display <module.name>"
            match = re.match(r"^\s*(?:.*\s+<)?([^<>\s]+)>?\s*$", line)
            if match:
                module_name = match.group(1)

                # Skip hidden modules
                if should_hide_module(module_name, hidden_modules):
                    continue

                # Create short display name entry
                short_name = get_short_name(module_name)
                if short_name != module_name:
                    result_lines.append(f"{current_indent}{short_name} <{module_name}>")
                else:
                    result_lines.append(line)
            else:
                result_lines.append(line)
        else:
            result_lines.append(line)

    return "\n".join(result_lines)


def clean_autodocs():
    """Main function to clean up autodocs RST files."""
    hidden_modules = get_hidden_modules()
    print(f"Hidden modules: {hidden_modules}")

    if not AUTODOCS_DIR.exists():
        print(f"Autodocs directory not found: {AUTODOCS_DIR}")
        return

    # Process all RST files
    rst_files = list(AUTODOCS_DIR.glob("*.rst"))
    print(f"Found {len(rst_files)} RST files")

    files_deleted = 0
    files_updated = 0

    for rst_file in rst_files:
        module_name = rst_file.stem  # e.g., 'earthkit.transforms.temporal'

        # Delete files for hidden/private modules
        if should_hide_module(module_name, hidden_modules):
            print(f"Deleting: {rst_file.name}")
            rst_file.unlink()
            files_deleted += 1
            continue

        # Clean up toctree entries in remaining files
        content = rst_file.read_text()
        new_content = clean_toctree(content, hidden_modules)

        if new_content != content:
            rst_file.write_text(new_content)
            print(f"Updated: {rst_file.name}")
            files_updated += 1

    print(f"\nSummary: {files_deleted} files deleted, {files_updated} files updated")


if __name__ == "__main__":
    clean_autodocs()
